version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
      - sidekiq
    environment:
      DATABASE_URL: mysql2://user:password@db:3306/chat_app_api
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_app_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: mysql2://user:password@db:3306/chat_app_api
      MYSQL_DATABASE: chat_app_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password

